---

SITE_NAME: choice-reports
SITE_DISPLAY_NAME: CHOICE Reports
SITE_HOST_NAME: localhost
SITE_PORT: 12280
SITE_BASE_URL: "http://localhost:12280"
SITE_ZONE: America/Denver
SITE_LOCALE: en-US
SITE_INSTANCES: 5
WORKER_POOL_SIZE: 2
VERTX_WARNING_EXCEPTION_SECONDS: 10
CLUSTER_HOST_NAME: localhost
CLUSTER_PORT: 12281
GITHUB_ORG: "CHOICE-Humanitarian"
QUAYIO_ORG: "computate"
PROJECT_POWERED_BY_URL: "https://access.redhat.com/products/openshift-online-red-hat"
PROJECT_POWERED_BY_NAME: "OpenShift Online"
PROJECT_POWERED_BY_IMAGE_URI: "/svg/openshift.svg"

STATIC_BASE_URL: "http://localhost:12280/static"
STATIC_PATH: "/usr/local/src/choice-reports-static"

API_CONTACT_EMAIL: 
API_COUNTER_PAUSE: 10
API_COUNTER_RESUME: 5
API_COUNTER_FETCH: 10

JDBC_HOST: localhost
JDBC_PORT: 5432
JDBC_DATABASE: choice-reports
JDBC_USERNAME: choice-reports
JDBC_PASSWORD: 
JDBC_MAX_POOL_SIZE: 10
JDBC_MAX_WAIT_QUEUE_SIZE: 1000

AUTH_REALM: 
AUTH_RESOURCE: 
AUTH_SECRET: 
AUTH_HOST_NAME: 
AUTH_PORT: 443
AUTH_SSL: true
AUTH_SSL_REQUIRED: all
AUTH_TOKEN_URI: /auth/realms/AUTH_REALM/protocol/openid-connect/token

ZOOKEEPER_HOST_NAME: localhost
ZOOKEEPER_PORT: 2181

SOLR_URL: http://localhost:8983/solr/choice-reports
SOLR_HOST_NAME: localhost
SOLR_PORT: 8983
SOLR_COLLECTION: choice-reports
SOLR_COLLECTION_COMPUTATE: computate
SOLR_WORKER_COMMIT_WITHIN_MILLIS: 10000

EMAIL_HOST: 
EMAIL_PORT: 
EMAIL_SSL: 
EMAIL_AUTH: 
EMAIL_USERNAME: 
EMAIL_PASSWORD: 
EMAIL_FROM: 
EMAIL_ADMIN: 

REFRESH_DATA_PAUSE_IN_SECONDS: 10
ENABLE_REFRESH_DATA: false
ENABLE_REFRESH_DATA_ChoiceDonor: true
ENABLE_REFRESH_DATA_ChoiceReport: true
ENABLE_REFRESH_DATA_SitePage: true
ENABLE_REFRESH_DATA_ReportEvent: true
ENABLE_REFRESH_DATA_ReportNarrative: true
ENABLE_REFRESH_DATA_ReportSchedule: true
ENABLE_REFRESH_DATA_ReportType: true
ENABLE_REFRESH_DATA_SiteHtm: true

ENABLE_IMPORT_DATA: true
ENABLE_IMPORT_DATA_ChoiceDonor: true
ENABLE_IMPORT_DATA_ChoiceReport: true
ENABLE_IMPORT_DATA_SitePage: true
ENABLE_IMPORT_DATA_ReportEvent: true
ENABLE_IMPORT_DATA_ReportNarrative: true
ENABLE_IMPORT_DATA_ReportSchedule: true
ENABLE_IMPORT_DATA_ReportType: true
ENABLE_IMPORT_DATA_SiteHtm: true

# The Auth roles required to be an admin in the site. 
AUTH_ROLES_ADMIN: ['SiteAdmin']
# The Auth roles required to add and modify site user records. 
AUTH_ROLES_REQUIRED_SiteUser: ['SiteAdmin']
# The Auth roles required to add and modify donor records. 
AUTH_ROLES_REQUIRED_ChoiceDonor: ['SiteAdmin']
# The Auth roles required to add and modify report records. 
AUTH_ROLES_REQUIRED_ChoiceReport: ['SiteAdmin']
# The Auth roles required to add and modify article records. 
AUTH_ROLES_REQUIRED_SitePage: ['SiteAdmin']
# The Auth roles required to add and modify report event records. 
AUTH_ROLES_REQUIRED_ReportEvent: ['SiteAdmin']
# The Auth roles required to add and modify report narrative records. 
AUTH_ROLES_REQUIRED_ReportNarrative: ['SiteAdmin']
# The Auth roles required to add and modify report schedule records. 
AUTH_ROLES_REQUIRED_ReportSchedule: ['SiteAdmin']
# The Auth roles required to add and modify report type records. 
AUTH_ROLES_REQUIRED_ReportType: ['SiteAdmin']
# The Auth roles required to add and modify HTML records. 
AUTH_ROLES_REQUIRED_SiteHtm: ['SiteAdmin']
