
SITE_HOST_NAME: localhost
SITE_PORT: 10781
SITE_BASE_URL: http://localhost:10781
SITE_ZONE: America/Denver
SITE_LOCALE: en-US
SITE_INSTANCES: 5
WORKER_POOL_SIZE: 2
VERTX_WARNING_EXCEPTION_SECONDS: 10
CLUSTER_HOST_NAME: localhost
CLUSTER_PORT: 10881

STATIC_BASE_URL: http://localhost:10781/static
STATIC_PATH: /usr/local/src/choice-reports-static

API_CONTACT_EMAIL: 
API_COUNTER_PAUSE: 10
API_COUNTER_RESUME: 5

JDBC_HOST: localhost
JDBC_PORT: 5432
JDBC_DATABASE: choice
JDBC_USERNAME: choice
JDBC_PASSWORD: 
JDBC_MAX_POOL_SIZE: 10
JDBC_MAX_WAIT_QUEUE_SIZE: 1000

AUTH_REALM: 
AUTH_RESOURCE: 
AUTH_SECRET: 
AUTH_HOST_NAME: 
AUTH_PORT: 443
AUTH_SSL: true
AUTH_SSL_REQUIRED: all
AUTH_TOKEN_URI: /auth/realms/AUTH_REALM/protocol/openid-connect/token

ZOOKEEPER_HOST_NAME: localhost
ZOOKEEPER_PORT: 2181

SOLR_URL: http://localhost:8983/solr/choice-reports
SOLR_HOST_NAME: localhost
SOLR_PORT: 8983
SOLR_COLLECTION: choice-reports
SOLR_COLLECTION_COMPUTATE: computate

EMAIL_HOST: 
EMAIL_PORT: 
EMAIL_SSL: 
EMAIL_AUTH: 
EMAIL_USERNAME: 
EMAIL_PASSWORD: 
EMAIL_FROM: 
EMAIL_ADMIN: 

TIMER_DB_SOLR_SYNC_IN_SECONDS: 1
ENABLE_DB_SOLR_SYNC: false
ENABLE_DB_SOLR_SYNC_TrafficContraband: true
ENABLE_DB_SOLR_SYNC_SearchBasis: true
ENABLE_DB_SOLR_SYNC_TrafficSearch: true
ENABLE_DB_SOLR_SYNC_TrafficPerson: true
ENABLE_DB_SOLR_SYNC_TrafficStop: true

ENABLE_REFRESH_DATA: false
ENABLE_REFRESH_DATA_TrafficContraband: true
ENABLE_REFRESH_DATA_SearchBasis: true
ENABLE_REFRESH_DATA_TrafficSearch: true
ENABLE_REFRESH_DATA_TrafficPerson: true
ENABLE_REFRESH_DATA_TrafficStop: true

ENABLE_IMPORT_DATA: true

ENABLE_IMPORT_DATA_ChoiceDonor: true
#IMPORT_DATA_START_TIME_ChoiceDonor: 00:00 America/Denver
#IMPORT_DATA_PERIOD_ChoiceDonor: 1 hour

ENABLE_IMPORT_DATA_ChoiceImage: true
#IMPORT_DATA_START_TIME_ChoiceImage: 00:01 America/Denver
#IMPORT_DATA_PERIOD_ChoiceImage: 1 hour
IMPORT_DATA_ReportType:
  - typeName: Employee Giving - Bronze
  - typeName: Employee Giving - Gold
  - typeName: Expeditions
  - typeName: Village Members
  - typeName: Grantors
  - typeName: Projects (regular)
  - typeName: Programs - Parent
  - typeName: Projects - Child
  - typeName: Events
  - typeName: Annual Report

ACS_API_YEAR: 2019

NEOCITIES_HOST_NAME: neocities.org
NEOCITIES_PORT: 443
NEOCITIES_SSL: true
NEOCITIES_API_UPLOAD: /api/upload
NEOCITIES_API_DELETE: /api/delete
NEOCITIES_API_LIST: /api/list
NEOCITIES_API_INFO: /api/info
NEOCITIES_API_RENAME: /api/rename
