
CREATE TABLE IF NOT EXISTS SiteUser();
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userId text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userEmail text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFirstName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userLastName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userFullName text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS seeArchived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS seeDeleted boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE SiteUser ADD COLUMN IF NOT EXISTS userKey bigint;

CREATE TABLE IF NOT EXISTS ChoiceDonor();
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS donorFullName text;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS donorParentName text;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS donorId bigint;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS donorAttributeId text;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS donorInKind bigint;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS donorTotal decimal;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS donorYtd decimal;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS donorQ1 decimal;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS donorQ2 decimal;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS donorQ3 decimal;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS donorQ4 decimal;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS donorLogoFilename text;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE ChoiceDonor ADD COLUMN IF NOT EXISTS userKey bigint;

CREATE TABLE IF NOT EXISTS ChoiceReport();
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS donorKey bigint references ChoiceDonor(pk);
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS donorFullName text;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS donorParentName text;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS donorId bigint;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS donorAttributeId text;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS donorInKind bigint;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS donorTotal decimal;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS donorYtd decimal;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS donorQ1 decimal;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS donorQ2 decimal;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS donorQ3 decimal;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS donorQ4 decimal;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS donorLogoFilename text;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE ChoiceReport ADD COLUMN IF NOT EXISTS userKey bigint;

CREATE TABLE IF NOT EXISTS ReportType();
ALTER TABLE ReportType ADD COLUMN IF NOT EXISTS typeName text;
ALTER TABLE ReportType ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE ReportType ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE ReportType ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE ReportType ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE ReportType ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE ReportType ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE ReportType ADD COLUMN IF NOT EXISTS userKey bigint;

CREATE TABLE IF NOT EXISTS ReportSchedule();
ALTER TABLE ReportSchedule ADD COLUMN IF NOT EXISTS typeKey bigint references ReportType(pk);
ALTER TABLE ReportSchedule ADD COLUMN IF NOT EXISTS scheduleName text;
ALTER TABLE ReportSchedule ADD COLUMN IF NOT EXISTS frequencyOneTime boolean;
ALTER TABLE ReportSchedule ADD COLUMN IF NOT EXISTS frequencyTimesPerYear integer;
ALTER TABLE ReportSchedule ADD COLUMN IF NOT EXISTS frequencyYearsAfterCompletion integer;
ALTER TABLE ReportSchedule ADD COLUMN IF NOT EXISTS firstDueDate date;
ALTER TABLE ReportSchedule ADD COLUMN IF NOT EXISTS dataPullDate date;
ALTER TABLE ReportSchedule ADD COLUMN IF NOT EXISTS dataSources text;
ALTER TABLE ReportSchedule ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE ReportSchedule ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE ReportSchedule ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE ReportSchedule ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE ReportSchedule ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE ReportSchedule ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE ReportSchedule ADD COLUMN IF NOT EXISTS userKey bigint;

CREATE TABLE IF NOT EXISTS ReportNarrative();
ALTER TABLE ReportNarrative ADD COLUMN IF NOT EXISTS scheduleKey bigint references ReportSchedule(pk);
ALTER TABLE ReportNarrative ADD COLUMN IF NOT EXISTS assigneeKey bigint references SiteUser(pk);
ALTER TABLE ReportNarrative ADD COLUMN IF NOT EXISTS narrativeName text;
ALTER TABLE ReportNarrative ADD COLUMN IF NOT EXISTS pullStartDate date;
ALTER TABLE ReportNarrative ADD COLUMN IF NOT EXISTS pullEndDate date;
ALTER TABLE ReportNarrative ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE ReportNarrative ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE ReportNarrative ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE ReportNarrative ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE ReportNarrative ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE ReportNarrative ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE ReportNarrative ADD COLUMN IF NOT EXISTS userKey bigint;

CREATE TABLE IF NOT EXISTS ReportEvent();
ALTER TABLE ReportEvent ADD COLUMN IF NOT EXISTS scheduleKey bigint references ReportSchedule(pk);
ALTER TABLE ReportEvent ADD COLUMN IF NOT EXISTS assigneeKey bigint references SiteUser(pk);
ALTER TABLE ReportEvent ADD COLUMN IF NOT EXISTS eventName text;
ALTER TABLE ReportEvent ADD COLUMN IF NOT EXISTS eventDate date;
ALTER TABLE ReportEvent ADD COLUMN IF NOT EXISTS pk bigserial primary key;
ALTER TABLE ReportEvent ADD COLUMN IF NOT EXISTS inheritPk text;
ALTER TABLE ReportEvent ADD COLUMN IF NOT EXISTS created timestamp with time zone;
ALTER TABLE ReportEvent ADD COLUMN IF NOT EXISTS archived boolean;
ALTER TABLE ReportEvent ADD COLUMN IF NOT EXISTS deleted boolean;
ALTER TABLE ReportEvent ADD COLUMN IF NOT EXISTS sessionId text;
ALTER TABLE ReportEvent ADD COLUMN IF NOT EXISTS userKey bigint;
