DROP TABLE SiteUser CASCADE;
DROP TABLE ChoiceDonor CASCADE;
DROP TABLE ChoiceReport CASCADE;
DROP TABLE ReportType CASCADE;
DROP TABLE ReportSchedule CASCADE;
DROP TABLE ReportNarrative CASCADE;
DROP TABLE ReportEvent CASCADE;
