APP_NAME: choice-reports

LANGUAGE_NAME: enUS
APP_PATH_enUS: /usr/local/src/choice-reports
DOMAIN_NAME: heytate.com
DOMAIN_PACKAGE_NAME: org.choicehumanitarian.reports.enus
SUFFIX_SRC_MAIN_JAVA: /src/main/java
SUFFIX_SRC_GEN_JAVA: /src/gen/java
RELATIVE_PATHS_TO_WATCH: src/main/java/org/choicehumanitarian/reports/enus

JDBC_HOST: localhost
JDBC_PORT: 5432
JDBC_DATABASE: choice-reports
JDBC_USERNAME: choice-reports
JDBC_PASSWORD: ojmKJlScqw
SITE_HOST_NAME: choice-reports-dev.example.com
SITE_BASE_URL: http://localhost:10981
AUTH_REALM: COMPUTATE.ORG
AUTH_RESOURCE: computate.org
AUTH_SECRET: eece2685-569a-443f-badb-f8283c5ffce0
AUTH_URL: https://sso.computate.org/auth
AUTH_TOKEN_URI: /auth/realms/COMPUTATE.ORG/protocol/openid-connect/token
AUTH_HOST_NAME: sso.computate.org
AUTH_PORT: 443
AUTH_SSL: true
AUTH_SSL_REQUIRED: all
AUTH_ROLES_ADMIN:
  - SiteAdmin
SITE_PORT: 10981
SOLR_URL: http://localhost:8983/solr/choice-reports
SOLR_URL_COMPUTATE: http://localhost:8983/solr/computate
API_CONTACT_EMAIL: ...
SITE_ZONE: America/Denver
SITE_LOCALE: en-US
STATIC_BASE_URL: http://localhost:10981/static
STATIC_PATH: /usr/local/src/choice-reports-static
TEMPLATE_PATH: /usr/local/src/choice-reports-static/template
EMAIL_HOST: 
EMAIL_PORT: 
EMAIL_SSL: 
EMAIL_AUTH: 
EMAIL_USERNAME: 
EMAIL_PASSWORD: 
EMAIL_FROM: 
EMAIL_ADMIN: 
SQL_TABLES: True
# Set the userKey of the user creating an object in the database. 
ENABLE_USER_KEY: true
# Set the sessionId of the user session creating an object in the database. 
ENABLE_SESSION_ID: true
# Enable an object in the database to be deleted. 
ENABLE_DELETED: true
# Enable an object in the database to be archived. 
ENABLE_ARCHIVED: true
ENABLE_IMPORT_DATA: true

AUTH_ROLES_ADMIN: [ SiteAdmin ]
AUTH_ROLES_REQUIRED_ChoiceDonor: [ SiteAdmin ]
AUTH_ROLES_REQUIRED_ChoiceReport: [ SiteAdmin ]
AUTH_ROLES_REQUIRED_SiteUser: [ SiteAdmin ]

DOMO_HOST_NAME: api.domo.com
DOMO_PORT: 443
DOMO_SSL: true
DOMO_AUTH_TOKEN_URI: /oauth/token
DOMO_AUTH_SCOPE: data workflow audit buzz user account dashboard
DOMO_AUTH_CLIENT_ID: 1e5410a5-baa6-4ad9-a969-ce7e7a4dd1bf
DOMO_AUTH_CLIENT_SECRET: 98f3bac5015d2ebb36eb6c73593717e5df96fbb398813dfa3dd0a89cbdeff11c
DOMO_DATASET_CPP_URI: /v1/datasets/query/execute/ba2fc0d4-345e-4b9b-b60e-1379e2a06a26

