---
# Label: ansible_project_deployment_config
# Title: create the Ansible template for the project deployment config in OpenShift
# Mission: create the Ansible template for the project deployment config in OpenShift
# Milestone: Automate Project Deployment
# Column: Automate Project Deployment

apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
spec:
  replicas: 1
  selector:
    app: "{{ APP_NAME }}"
    deploymentconfig: "{{ APP_NAME }}"
  strategy:
    activeDeadlineSeconds: 21600
    recreateParams:
      timeoutSeconds: 600
    resources: {}
    type: Recreate
  template:
    metadata:
      labels:
        app: "{{ APP_NAME }}"
        deploymentconfig: "{{ APP_NAME }}"
    spec:
      containers:
        - imagePullPolicy: Always
          name: "{{ APP_NAME }}"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 8081
              name: cluster
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
          resources:
            limits:
              memory: '{{ APP_LIMITS_MEMORY }}'
              cpu: '{{ APP_LIMITS_CPU }}'
          env:
            - name: AUTH_REALM
              valueFrom:
                secretKeyRef:
                  key: AUTH_REALM
                  name: "{{ APP_NAME }}-secret"
            - name: AUTH_RESOURCE
              valueFrom:
                secretKeyRef:
                  key: AUTH_RESOURCE
                  name: "{{ APP_NAME }}-secret"
            - name: AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  key: AUTH_SECRET
                  name: "{{ APP_NAME }}-secret"
            - name: AUTH_HOST_NAME
              valueFrom:
                secretKeyRef:
                  key: AUTH_HOST_NAME
                  name: "{{ APP_NAME }}-secret"
            - name: AUTH_PORT
              valueFrom:
                secretKeyRef:
                  key: AUTH_PORT
                  name: "{{ APP_NAME }}-secret"
            - name: AUTH_SSL
              valueFrom:
                secretKeyRef:
                  key: AUTH_SSL
                  name: "{{ APP_NAME }}-secret"
            - name: AUTH_TOKEN_URI
              value: "{{ AUTH_TOKEN_URI }}"
            - name: EMAIL_AUTH
              valueFrom:
                secretKeyRef:
                  key: EMAIL_AUTH
                  name: "{{ APP_NAME }}-secret"
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  key: EMAIL_FROM
                  name: "{{ APP_NAME }}-secret"
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  key: EMAIL_HOST
                  name: "{{ APP_NAME }}-secret"
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: EMAIL_PASSWORD
                  name: "{{ APP_NAME }}-secret"
            - name: EMAIL_PORT
              valueFrom:
                secretKeyRef:
                  key: EMAIL_PORT
                  name: "{{ APP_NAME }}-secret"
            - name: EMAIL_SSL
              valueFrom:
                secretKeyRef:
                  key: EMAIL_SSL
                  name: "{{ APP_NAME }}-secret"
            - name: EMAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  key: EMAIL_USERNAME
                  name: "{{ APP_NAME }}-secret"
            - name: JDBC_HOST
              valueFrom:
                secretKeyRef:
                  key: JDBC_HOST
                  name: "{{ APP_NAME }}-secret"
            - name: JDBC_PORT
              valueFrom:
                secretKeyRef:
                  key: JDBC_PORT
                  name: "{{ APP_NAME }}-secret"
            - name: JDBC_DATABASE
              valueFrom:
                secretKeyRef:
                  key: JDBC_DATABASE
                  name: "{{ APP_NAME }}-secret"
            - name: JDBC_USERNAME
              valueFrom:
                secretKeyRef:
                  key: JDBC_USERNAME
                  name: "{{ APP_NAME }}-secret"
            - name: JDBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: JDBC_PASSWORD
                  name: "{{ APP_NAME }}-secret"
            - name: SSL_PASSTHROUGH
              valueFrom:
                secretKeyRef:
                  key: SSL_PASSTHROUGH
                  name: "{{ APP_NAME }}-secret"
            - name: SSL_ALIAS
              valueFrom:
                secretKeyRef:
                  key: SSL_ALIAS
                  name: "{{ APP_NAME }}-secret"
            - name: SSL_JKS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SSL_JKS_PASSWORD
                  name: "{{ APP_NAME }}-secret"
            - name: SSL_JKS_PATH
              valueFrom:
                secretKeyRef:
                  key: SSL_JKS_PATH
                  name: "{{ APP_NAME }}-secret"
            - name: SSL_KEYSTORE_PATH
              valueFrom:
                secretKeyRef:
                  key: SSL_KEYSTORE_PATH
                  name: "{{ APP_NAME }}-secret"
            - name: ACS_API_KEY
              valueFrom:
                secretKeyRef:
                  key: ACS_API_KEY
                  name: "{{ APP_NAME }}-secret"

            - name: FTP_SYNC_HOST_NAME
              valueFrom:
                secretKeyRef:
                  key: FTP_SYNC_HOST_NAME
                  name: "{{ APP_NAME }}-secret"
            - name: FTP_SYNC_PORT
              valueFrom:
                secretKeyRef:
                  key: FTP_SYNC_PORT
                  name: "{{ APP_NAME }}-secret"
            - name: FTP_SYNC_USERNAME
              valueFrom:
                secretKeyRef:
                  key: FTP_SYNC_USERNAME
                  name: "{{ APP_NAME }}-secret"
            - name: FTP_SYNC_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: FTP_SYNC_PASSWORD
                  name: "{{ APP_NAME }}-secret"
            - name: FTP_SYNC_REMOTE_PATH
              valueFrom:
                secretKeyRef:
                  key: FTP_SYNC_REMOTE_PATH
                  name: "{{ APP_NAME }}-secret"

            - name: OPENSHIFT_SERVICE
              value: "{{ APP_NAME }}"
            - name: CLUSTER_PORT
              value: "8081"
            - name: ZOOKEEPER_HOST_NAME
              value: "{{ ZOOKEEPER_HOST_NAME }}"
            - name: ZOOKEEPER_PORT
              value: "{{ ZOOKEEPER_PORT }}"
            - name: SOLR_HOST_NAME
              value: "{{ SOLR_HOST_NAME }}"
            - name: SOLR_PORT
              value: "{{ SOLR_PORT }}"
            - name: SOLR_URL
              value: "http://{{ SOLR_HOST_NAME}}:{{SOLR_PORT}}/solr/{{APP_SOLR_COLLECTION_ENUS }}"
            - name: SITE_HOST_NAME
              value: "{{ APP_SITE_HOST_NAME_ENUS }}"
            - name: SITE_PORT
              value: "{{ APP_SITE_PORT_ENUS }}"
            - name: SITE_BASE_URL
              value: "{{ APP_SITE_BASE_URL_ENUS }}"
            - name: STATIC_BASE_URL
              value: "{{ APP_STATIC_BASE_URL }}"
            - name: STATIC_PATH
              value: "{{ APP_STATIC_PATH }}"
            - name: SITE_ZONE
              value: "{{ APP_SITE_ZONE_ENUS }}"
            - name: JAVA_MAIN_CLASS
              value: "{{ APP_JAVA_MAIN_CLASS_ENUS }}"
            - name: SITE_INSTANCES
              value: "{{ SITE_INSTANCES }}"
            - name: WORKER_POOL_SIZE
              value: "{{ WORKER_POOL_SIZE }}"

            - name: READ_BUFFER_SIZE
              value: "{{ READ_BUFFER_SIZE }}"
            - name: API_COUNTER_FETCH
              value: "{{ API_COUNTER_FETCH }}"
            - name: API_COUNTER_RESUME
              value: "{{ API_COUNTER_RESUME }}"
            - name: API_COUNTER_FETCH
              value: "{{ API_COUNTER_FETCH }}"
            - name: ENABLE_IMPORT_DATA
              value: "{{ ENABLE_IMPORT_DATA }}"
            - name: TIMER_DB_SOLR_SYNC_IN_SECONDS
              value: "{{ TIMER_DB_SOLR_SYNC_IN_SECONDS }}"
            - name: ENABLE_DB_SOLR_SYNC
              value: "{{ ENABLE_DB_SOLR_SYNC }}"
            - name: ENABLE_DB_SOLR_SYNC_TrafficContraband
              value: "{{ ENABLE_DB_SOLR_SYNC_TrafficContraband }}"
            - name: ENABLE_DB_SOLR_SYNC_SearchBasis
              value: "{{ ENABLE_DB_SOLR_SYNC_SearchBasis }}"
            - name: ENABLE_DB_SOLR_SYNC_TrafficSearch
              value: "{{ ENABLE_DB_SOLR_SYNC_TrafficSearch }}"
            - name: ENABLE_DB_SOLR_SYNC_TrafficPerson
              value: "{{ ENABLE_DB_SOLR_SYNC_TrafficPerson }}"
            - name: ENABLE_DB_SOLR_SYNC_TrafficStop
              value: "{{ ENABLE_DB_SOLR_SYNC_TrafficStop }}"
            - name: ENABLE_DB_SOLR_SYNC_SiteAgency
              value: "{{ ENABLE_DB_SOLR_SYNC_SiteAgency }}"
            - name: ENABLE_REFRESH_DATA
              value: "{{ ENABLE_REFRESH_DATA }}"
            - name: ENABLE_REFRESH_DATA_TrafficContraband
              value: "{{ ENABLE_REFRESH_DATA_TrafficContraband }}"
            - name: ENABLE_REFRESH_DATA_SearchBasis
              value: "{{ ENABLE_REFRESH_DATA_SearchBasis }}"
            - name: ENABLE_REFRESH_DATA_TrafficSearch
              value: "{{ ENABLE_REFRESH_DATA_TrafficSearch }}"
            - name: ENABLE_REFRESH_DATA_TrafficPerson
              value: "{{ ENABLE_REFRESH_DATA_TrafficPerson }}"
            - name: ENABLE_REFRESH_DATA_TrafficStop
              value: "{{ ENABLE_REFRESH_DATA_TrafficStop }}"
            - name: TIMER_DB_SOLR_SYNC_IN_SECONDS
              value: "{{ TIMER_DB_SOLR_SYNC_IN_SECONDS }}"
            - name: ENABLE_FTP_SYNC
              value: "{{ ENABLE_FTP_SYNC }}"
            - name: ENABLE_FTP_SYNC_TrafficStop
              value: "{{ ENABLE_FTP_SYNC_TrafficStop }}"
            - name: ENABLE_FTP_SYNC_TrafficPerson
              value: "{{ ENABLE_FTP_SYNC_TrafficPerson }}"
            - name: ENABLE_FTP_SYNC_TrafficSearch
              value: "{{ ENABLE_FTP_SYNC_TrafficSearch }}"
            - name: ENABLE_FTP_SYNC_SearchBasis
              value: "{{ ENABLE_FTP_SYNC_SearchBasis }}"
            - name: ENABLE_FTP_SYNC_TrafficContraband
              value: "{{ ENABLE_FTP_SYNC_TrafficContraband }}"
            - name: FTP_SYNC_PATH_ZIP
              value: "{{ FTP_SYNC_PATH_ZIP }}"
            - name: FTP_SYNC_PATH_TrafficStop
              value: "{{ FTP_SYNC_PATH_TrafficStop }}"
            - name: FTP_SYNC_PATH_TrafficPerson
              value: "{{ FTP_SYNC_PATH_TrafficPerson }}"
            - name: FTP_SYNC_PATH_TrafficSearch
              value: "{{ FTP_SYNC_PATH_TrafficSearch }}"
            - name: FTP_SYNC_PATH_TrafficContraband
              value: "{{ FTP_SYNC_PATH_TrafficContraband }}"
            - name: FTP_SYNC_PATH_TrafficSearchBasis
              value: "{{ FTP_SYNC_PATH_TrafficSearchBasis }}"
            - name: FTP_MAX_RECORD_SIZE
              value: "{{ FTP_MAX_RECORD_SIZE }}"
            - name: AUTH_ROLES_REQUIRED_ChoiceDonor
              value: "{{ AUTH_ROLES_ADMIN }}"
            - name: AUTH_ROLES_REQUIRED_ChoiceDonor
              value: "{{ AUTH_ROLES_REQUIRED_ChoiceDonor }}"
            - name: AUTH_ROLES_REQUIRED_ChoiceReport
              value: "{{ AUTH_ROLES_REQUIRED_ChoiceReport }}"
            - name: AUTH_ROLES_REQUIRED_SiteUser
              value: "{{ AUTH_ROLES_REQUIRED_SiteUser }}"
            - name: DOMO_HOST_NAME
              value: "{{ DOMO_HOST_NAME }}"
            - name: DOMO_PORT
              value: "{{ DOMO_PORT }}"
            - name: DOMO_SSL 
              value: "{{ DOMO_SSL }}"
            - name: DOMO_AUTH_TOKEN_URI
              value: "{{ DOMO_AUTH_TOKEN_URI }}"
            - name: DOMO_AUTH_SCOPE
              value: "{{ DOMO_AUTH_SCOPE }}"
            - name: DOMO_AUTH_CLIENT_ID
              value: "{{ DOMO_AUTH_CLIENT_ID }}"
            - name: DOMO_AUTH_CLIENT_SECRET
              value: "{{ DOMO_AUTH_CLIENT_SECRET }}"
            - name: DOMO_DATASET_CPP_URI
              value: "{{ DOMO_DATASET_CPP_URI }}"
          volumeMounts:
            - mountPath: /opt/keystore
              name: volume-keystore
              readOnly: true
            - mountPath: /opt/static/template/enUS
              name: volume-template
              readOnly: true
      volumes:
        - name: volume-keystore
          secret:
            defaultMode: 420
            secretName: "{{ APP_NAME }}-keystore"
        - name: volume-template
          configMap:
            defaultMode: 420
            name: "{{ APP_NAME }}-template"
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
          - {{ APP_NAME }}
        from:
          kind: ImageStreamTag
          name: '{{ APP_NAME }}:latest'
          namespace: "{{ APP_NAMESPACE }}"
      type: ImageChange
    - type: ConfigChange
